---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  module-validation:
    uses: appvia/appvia-cicd-workflows/.github/workflows/terraform-module-validation.yml@74f3dc641cd75d4ac5be3c1eecf04ba094eb9276 # main
    name: Module Validation
    with:
      working-directory: .
